FROM golang
LABEL maintainer="Pelend @ #nakkiservo"
LABEL description="SlackWiener backend"


RUN go get github.com/nakkiservo/slackwiener_backend
WORKDIR /go/src/github.com/nakkiservo/slackwiener_backend
RUN go get ./
RUN make
ADD app_config.toml ./build
ADD ../server.crt ./build
ADD ../server.key ./build

WORKDIR ./build
EXPOSE 3000


ENTRYPOINT ["./server"]
